{
 "title": "Node Metrics",
 "description": "cpu memroy disk IO network temperature",
 "tags": [ "instance" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d"
   },
   {
    "name": "node",
    "label": "host instance",
    "query": {
     "query": "label_values(node_exporter_build_info{},instance)"
    }
   },
   {
    "name": "maxmount",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Basic info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "$node", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "node" },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "cpu cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "system disk",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes {instance=~\"$node\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "cpu usage（5m）",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU iowait（5m）",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100"
    }
   ]
  },
  {
   "title": "partion ($maxmount) usage",
   "type": "gauge",
   "description": "Obtain the maximum partition through the variable maxmount.",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "opend file descriptor",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Load average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_1m"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_5m"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_15m"
    }
   ]
  },
  {
   "title": "CPU usage、disk I/O time（%）",
   "type": "graph",
   "description": "node_disk_io_time_seconds_total",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[2m])) by (instance)",
     "legendFormat": "{{instance}}_System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[2m])) by (instance)",
     "legendFormat": "{{instance}}_User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[2m])) by (instance)",
     "legendFormat": "{{instance}}_Iowait"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[2m])",
     "legendFormat": "{{instance}}_{{device}}_per second I/O%"
    }
   ]
  },
  {
   "title": "Partion usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}-node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext4|xfs\"}",
     "legendFormat": "{{mountpoint}}_usage"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory info",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
       "legendFormat": "{{instance}}_TotalMem"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
       "legendFormat": "{{instance}}_Used"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=~\"$node\"}",
       "legendFormat": "MEM_Free"
      },
      {
       "expr": "node_memory_Buffers_bytes{instance=~\"$node\"}",
       "legendFormat": "MEM_Buffers"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~\"$node\"}",
       "legendFormat": "MEM_Cached"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
       "legendFormat": "{{instance}}_Available"
      }
     ]
    },
    {
     "title": "Swap memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_SwapFree_bytes{instance=~\"$node\"}",
       "legendFormat": "Swap_Free"
      },
      {
       "expr": "node_memory_SwapCached_bytes{instance=~\"$node\"}",
       "legendFormat": "SwapCached"
      },
      {
       "expr": "node_memory_SwapTotal_bytes{instance=~\"$node\"}",
       "legendFormat": "SwapTotal"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network flow",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "bps", "label": "upload（-）/download（+）" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*|lxc.*|nodelocaldns|cilium.*'}[5m])*8",
       "legendFormat": "{{instance}}_{{device}}_in receive"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*|lxc.*|nodelocaldns|cilium.*'}[5m])*8",
       "legendFormat": "{{instance}}_{{device}}_out transmit"
      }
     ]
    },
    {
     "title": "TCP connect info",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
       "legendFormat": "{{instance}}_ESTABLISHED"
      },
      {
       "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
       "legendFormat": "{{instance}}_TCP_tw"
      },
      {
       "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~'$node'}[1m])",
       "legendFormat": "{{instance}}_ActiveOpens"
      },
      {
       "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~'$node'}[1m])",
       "legendFormat": "{{instance}}_PassiveOpens"
      },
      {
       "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
       "legendFormat": "{{instance}}_TCP_alloc"
      },
      {
       "expr": "node_sockstat_TCP_inuse{instance=~'$node'}",
       "legendFormat": "{{instance}}_TCP_inuse"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk read write",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "disk read and write（IOPS）",
     "type": "graph",
     "description": "Reads completed: Reads completed per second for each disk partition\n\nWrites completed: \nIO now",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "iops", "label": "read（-）/write（+）I/O ops/sec" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\"}[2m])",
       "legendFormat": "{{instance}}_{{device}}_read"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\"}[2m])",
       "legendFormat": "{{instance}}_{{device}}_write"
      }
     ]
    },
    {
     "title": "disk io read write time",
     "type": "graph",
     "description": "Read time ms The number of seconds taken for each disk partition read operation\n\nWrite time ms\nIO time ms \nIO time weighted",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "s", "label": "read（-）/write（+）" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[2m])",
       "legendFormat": "{{device}}"
      },
      {
       "expr": "irate(node_disk_io_time_weighted_seconds_total{instance=~\"$node\"}[2m])",
       "legendFormat": "{{device}}_weighting"
      },
      {
       "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$node\"}[2m])",
       "legendFormat": "{{instance}}_{{device}}_read"
      },
      {
       "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$node\"}[2m])",
       "legendFormat": "{{instance}}_{{device}}_write"
      }
     ]
    },
    {
     "title": "r/s",
     "type": "graph",
     "description": "The number of read operations per second=[Δrd_ios/Δt]",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{instance=~'$node'}[2m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "w/s",
     "type": "graph",
     "description": "The number of write operations per second=[Δwr_ios/Δt]",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(rate(node_disk_writes_completed_total{instance=~\"$node\"}[2m]))",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "r_await",
     "type": "graph",
     "description": "The average time required for each read operation=[ Δ Rd_ticks/ Δ Rd_ios not only includes the time required for hard disk device read operations, but also the waiting time in the kernel queue.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(node_disk_read_time_seconds_total {instance=~'$node'}[2m])) /(rate(node_disk_reads_completed_total {instance=~'$node'}[2m]))",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "w_await",
     "type": "graph",
     "description": "Average time required for each write operation=[ Δ Wr_ticks/ Δ Wr_ios not only includes the time required for hard disk device write operations, but also the waiting time in the kernel queue.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(node_disk_write_time_seconds_total {instance=~'$node'}[2m])) /(rate(node_disk_writes_completed_total {instance=~'$node'}[2m]))",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "rMiB/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(rate(node_disk_read_bytes_total {instance=~'$node'}[2m]))",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "wKiB/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(rate(node_disk_written_bytes_total {instance=~'$node'}[2m]))",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk read and write capacity size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "Bps", "label": "read（-）/write（+）" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[2m])",
       "legendFormat": "{{instance}}_{{device}}_read"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\"}[2m])",
       "legendFormat": "{{instance}}_{{device}}_write"
      }
     ]
    },
    {
     "title": "%util",
     "type": "graph",
     "description": "The busy ratio of this hard drive device=[ Δ Io_ticks/ Δ t] The time ratio indicating that the device has I/O (i.e. non idle), regardless of how much I/O there is, only considering whether there is",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
     "repeat": "idc",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$node\"}[2m])",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cpu temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu temperature",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "expr": "node_hwmon_temp_celsius{instance=~'$node'}",
       "legendFormat": "{{chip}}_{{sensor}}"
      }
     ]
    }
   ]
  }
 ]
}