apiVersion: v1
kind: Service
metadata:
  name: drycc-grafana
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    heritage: drycc
    app: drycc-grafana
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
  - name: grafana-tcp
    port: 3000
    targetPort: grafana
    protocol: TCP
  - name: alerting-tcp
    port: 9094
    targetPort: alerting
    protocol: TCP
  - name: alerting-udp
    port: 9094
    targetPort: alerting
    protocol: UDP
  - name: oauth2-tcp
    port: 4000
    targetPort: oauth2
    protocol: TCP
  - name: proxy-tcp
    port: 80
    targetPort: proxy
    protocol: TCP
  selector:
    app: drycc-grafana
