grafana:
  imageOrg: "drycc"
  imagePullPolicy: "Always"
  imageTag: "canary"
  imageRegistry: "registry.drycc.cc"
  # limitsCpu: "100m"
  # limitsMemory: "50Mi"
  nodeAffinityPreset:
    key: "drycc.cc/node"
    type: "soft"
    values:
    - "true"

  podAffinityPreset:
    key: "security"
    type: ""
    values:
    - "drycc-security"

  podAntiAffinityPreset:
    key: "app"
    type: "soft"
    values:
    - "drycc-monitor-grafana"

  # Service
  service:
    # Provide any additional service annotations
    annotations: {}

  persistence:
    enabled: false
    accessMode: ReadWriteOnce
    size: 5Gi
  # Any custom grafana environment variables
  # can be specified as key-value pairs under environment
  # this is usually a non required setting.
  environment:
    ALLOW_SIGN_UP: false
  # The passportUrl, passportKey and passportSecret are will no longer use the built-in passport component
  passportUrl: ""
  passportKey: ""
  passportSecret: ""

telegraf:
  imageOrg: "drycc"
  imagePullPolicy: "Always"
  imageTag: "canary"
  imageRegistry: "registry.drycc.cc"
  # limitsCpu: "100m"
  # limitsMemory: "50Mi"
  nodeAffinityPreset:
    key: "drycc.cc/node"
    type: "soft"
    values:
    - "true"

  podAffinityPreset:
    key: "security"
    type: ""
    values:
    - "drycc-security"

  podAntiAffinityPreset:
    key: "app"
    type: "soft"
    values:
    - "drycc-monitor-telegraf"

redis:
  replicas: 1
  port: "6379"

global:
  # Set the location of Workflow's component cluster
  #
  # Valid values are:
  # - on-cluster: Run component within the Kubernetes cluster
  # - off-cluster: component is running outside of the cluster and credentials and connection information will be provided.
  influxdbLocation: "on-cluster"
  prometheusLocation: "on-cluster"
  grafanaLocation: "on-cluster"
  redisLocation: "on-cluster"
  rabbitmqLocation: "on-cluster"
  storageLocation: "on-cluster"
  databaseLocation: "on-cluster"
  passportLocation: "on-cluster"
  registryLocation: "on-cluster"
  # Role-Based Access Control for Kubernetes >= 1.5
  rbac: false
  ingressClass: ""
  # A domain name consists of one or more parts.
  # Periods (.) are used to separate these parts.
  # Each part must be 1 to 63 characters in length and can contain lowercase letters, digits, and hyphens (-).
  # It must start and end with a lowercase letter or digit.
  clusterDomain: "cluster.local"
  # The public resolvable hostname to build your cluster with.
  #
  # This will be the hostname that is used to build endpoints such as "drycc.$HOSTNAME"
  platformDomain: ""
  # Whether cert_manager is enabled to automatically generate drycc certificates
  certManagerEnabled: true
