apiVersion: 1
datasources:
- name: Application Logs
  type: quickwit-quickwit-datasource
  access: proxy
  orgId: 1
  uid: application_logs
  url: http://localhost:4000/proxy/quickwit/drycc
  jsonData:
    index: logs-*
    logMessageField: log
  version: 1
  editable: false

- name: Prometheus on Drycc
  type: prometheus
  access: proxy
  orgId: 1
  uid: prometheus_on_drycc
  url: http://localhost:4000/proxy/prometheus/drycc
  isDefault: true
  jsonData:
    httpMethod: POST
  version: 1
  editable: false
