{
 "title": "Drycc App",
 "description": "General Drycc App metrics.",
 "tags": [ "drycc" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "60s",
 "templating": {
  "list": [
   { "name": "app", "label": "app", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "logs",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "id": "1",
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "kubernetes.namespace_name:${app:singlequote} kubernetes.container_name:drycc-controller"
    }
   ]
  },
  {
   "title": "Logs volume",
   "type": "timeseries",
   "description": "[Query Language](https://quickwit.io/docs/reference/query-language)",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "kubernetes.namespace_name:${app:singlequote} kubernetes.container_name:drycc-controller"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Load 5m",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 19, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$app\",container!=\"\"}[5m])) by (pod) \n/\n(\n  sum(container_spec_cpu_quota{namespace=~\"$app\",container!=\"\"}) by (pod)  / 10000000\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total CPU Cores",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((container_spec_cpu_quota{namespace=~\"$app\",container!=\"\"}/1000)/100)",
       "legendFormat": "Total CPU Cores"
      }
     ]
    },
    {
     "title": "CPUThrottling ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "(increase(container_cpu_cfs_throttled_periods_total{namespace=~\"$app\",container!=\"\" }[5m]))/\n(increase(container_cpu_cfs_periods_total{namespace=~\"$app\",container!=\"\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(container_memory_working_set_bytes{namespace=~\"$app\",container!=\"\"}) \n",
     "legendFormat": "Used Memory"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{namespace=~\"$app\",container!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"$app\"}[5m])) ",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"$app\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$app\"}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$app\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Volume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "IOPS Read",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=~\"$app\",container!=\"\"}[1m]))\n",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=~\"$app\",container!=\"\"}[1m])) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "IOPS Write",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=~\"$app\",container!=\"\"}[1m]))\n",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=~\"$app\",container!=\"\"}[1m])) by(pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}